# Generated by Django 6.0.4 on 2026-04-12 00:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='producto',
            table='producto',
        ),
    ]
