# Generated by Django 6.0.4 on 2026-04-12 01:00

import django.db.models.deletion
from django.db import migrations, models


DEFAULT_CATEGORIAS = {
    'tecnologia': ('Tecnologia', 'TEC'),
    'oficina': ('Oficina', 'OFI'),
    'hogar': ('Hogar', 'HOG'),
    'alimentos': ('Alimentos', 'ALI'),
    'otros': ('Otros', 'OTR'),
}


def _normalize(value):
    if not value:
        return 'otros'
    return str(value).strip().lower()


def _prefix_from_name(name, used_prefixes):
    base = ''.join(ch for ch in name.upper() if ch.isalnum())[:5] or 'CAT'
    prefix = base
    counter = 1
    while prefix in used_prefixes:
        suffix = str(counter)
        prefix = f"{base[: max(1, 5 - len(suffix))]}{suffix}"
        counter += 1
    used_prefixes.add(prefix)
    return prefix


def migrate_categoria_forward(apps, schema_editor):
    Categoria = apps.get_model('productos', 'Categoria')
    Producto = apps.get_model('productos', 'Producto')

    categoria_by_key = {}
    used_prefixes = set(
        Categoria.objects.values_list('prefijo_sku', flat=True)
    )

    for key, (nombre, prefijo) in DEFAULT_CATEGORIAS.items():
        categoria, _ = Categoria.objects.get_or_create(
            nombre=nombre,
            defaults={'prefijo_sku': prefijo, 'activa': True},
        )
        if categoria.prefijo_sku != prefijo:
            categoria.prefijo_sku = prefijo
            categoria.save(update_fields=['prefijo_sku'])
        used_prefixes.add(categoria.prefijo_sku)
        categoria_by_key[key] = categoria

    for producto in Producto.objects.all():
        key = _normalize(producto.categoria)
        categoria = categoria_by_key.get(key)
        if categoria is None:
            nombre = str(producto.categoria).strip().title() if producto.categoria else 'Otros'
            categoria = Categoria.objects.filter(nombre__iexact=nombre).first()
            if categoria is None:
                prefijo = _prefix_from_name(nombre, used_prefixes)
                categoria = Categoria.objects.create(
                    nombre=nombre,
                    prefijo_sku=prefijo,
                    activa=True,
                )
            categoria_by_key[key] = categoria
        producto.categoria_nueva_id = categoria.id
        producto.save(update_fields=['categoria_nueva'])


def migrate_categoria_reverse(apps, schema_editor):
    Producto = apps.get_model('productos', 'Producto')

    for producto in Producto.objects.select_related('categoria_nueva').all():
        categoria_nombre = 'otros'
        if producto.categoria_nueva_id and producto.categoria_nueva:
            categoria_nombre = producto.categoria_nueva.nombre.lower()
        producto.categoria = categoria_nombre
        producto.save(update_fields=['categoria'])


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_alter_producto_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80, unique=True)),
                ('prefijo_sku', models.CharField(max_length=5, unique=True)),
                ('activa', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
                'db_table': 'categoria',
                'ordering': ['nombre'],
            },
        ),
        migrations.AddField(
            model_name='producto',
            name='categoria_nueva',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='productos_temp',
                to='productos.categoria',
            ),
        ),
        migrations.RunPython(migrate_categoria_forward, migrate_categoria_reverse),
        migrations.RemoveField(
            model_name='producto',
            name='categoria',
        ),
        migrations.RenameField(
            model_name='producto',
            old_name='categoria_nueva',
            new_name='categoria',
        ),
        migrations.AlterField(
            model_name='producto',
            name='categoria',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name='productos',
                to='productos.categoria',
            ),
        ),
    ]
